using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Bitki.Infrastructure.Data;
using Bitki.Core.Entities;

namespace Bitki.Api.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PlantsController : ControllerBase
    {
        private readonly AppDbContext _context;

        public PlantsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: api/plants
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Plant>>> GetPlants()
        {
            return await _context.Plants.ToListAsync();
        }

        // GET: api/plants/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Plant>> GetPlant(int id)
        {
            var plant = await _context.Plants.FindAsync(id);

            if (plant == null)
            {
                return NotFound();
            }

            return plant;
        }

        // POST: api/plants
        [HttpPost]
        public async Task<ActionResult<Plant>> PostPlant(Plant plant)
        {
            // If the ID is generated by DB (serial), we should ignore what is passed or set it to 0.
            // But EF Core handles this if configured. 
            // The prompt says "Do not configure migrations or identity generation unless required by the existing schema."
            // Existing schema 'id' is likely serial.

            _context.Plants.Add(plant);
            await _context.SaveChangesAsync();

            return CreatedAtAction(nameof(GetPlant), new { id = plant.Id }, plant);
        }

        // PUT: api/plants/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutPlant(int id, Plant plant)
        {
            if (id != plant.Id)
            {
                return BadRequest();
            }

            _context.Entry(plant).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PlantExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // DELETE: api/plants/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeletePlant(int id)
        {
            var plant = await _context.Plants.FindAsync(id);
            if (plant == null)
            {
                return NotFound();
            }

            _context.Plants.Remove(plant);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool PlantExists(int id)
        {
            return _context.Plants.Any(e => e.Id == id);
        }

        // GET: api/plants/debug/columns?table=dbo.bitki
        [HttpGet("debug/columns")]
        public async Task<ActionResult<IEnumerable<string>>> GetColumns([FromQuery] string table)
        {
            var parts = table.Split('.');
            var schema = parts.Length > 1 ? parts[0] : "public";
            var tableName = parts.Length > 1 ? parts[1] : parts[0];

            var columns = await _context.Database
                .SqlQueryRaw<string>($"SELECT column_name || ' (' || data_type || ')' FROM information_schema.columns WHERE table_schema = '{schema}' AND table_name = '{tableName}'")
                .ToListAsync();
            return columns;
        }
    }
}
